Exercício 1 - Importe NumPy como np

In [1]:
import numpy as np

Exercício 2 - Crie uma matriz de 10 zeros

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Exercício 3 - Crie uma matriz de 10 ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Exercício 4 - Crie uma matriz de 10 cincos

In [13]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Exercício 5 - Crie um array de inteiros de 10 até 50

In [16]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Exercício 6 - Crie um array dos numeros pares de 10 até 50

In [17]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Exercício 7 - Criei uma matriz 3x3 com valores variando de 0 até 8

In [31]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Exercício 8 - Crie uma matriz identidade 3x3

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Exercício 9 - Use NumPy para gerar números aleatórios entre 0 e 1

In [37]:
np.random.rand(1)

array([0.17931871])

Exercício 10 - Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [44]:
np.random.randn(25)

array([ 0.01447829,  0.1559295 , -0.27638318,  0.86320899, -1.47305907,
        1.38247634, -0.48254974,  1.43620613, -0.28245995,  1.34701189,
       -0.0052832 , -1.33290502,  0.49004394, -2.49537117, -0.26361243,
       -0.08517844, -0.47322442, -1.42947285, -0.36491802, -1.96888172,
        0.04445713, -1.16604101, -0.02351401, -0.76840416,  0.18931627])