Exercício 1 - Crie um array NumPy com 1000000 e uma lista com 1000000. Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time). Qual objeto oferece melhor performance, array NumPy ou lista?

In [69]:
import numpy as np
npArray = np.arange(10000000)

In [70]:
npList = []
for i in range(0, 9999999):
    npList.append(i)

In [71]:
import datetime
import time
d1 = datetime.datetime.now()
npArray*2
d2 = datetime.datetime.now()
d3 = datetime.datetime.now()
npNewList = [j * 2 for j in npList]
d4 = datetime.datetime.now()

print('Multiplicação de npArray: \n Hora de Início: {} \n Hora de Término: {}'.format(d1, d2))
print('\n')
print('Multiplicação de npNewList: \n Hora de Início: {} \n Hora de Término: {}'.format(d3, d4))

Multiplicação de npArray: 
 Hora de Início: 2020-07-04 13:59:16.244693 
 Hora de Término: 2020-07-04 13:59:16.273675


Multiplicação de npNewList: 
 Hora de Início: 2020-07-04 13:59:16.273675 
 Hora de Término: 2020-07-04 13:59:17.356537


Exercício 2 - Crie um array de 10 elementos. Altere o valores de todos os elementos dos índices 5 a 8 para 0;

In [35]:
import numpy as np

In [36]:
ar = np.arange(10)

In [37]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
type(ar)

numpy.ndarray

In [39]:
ar[5:9] = 0

In [40]:
ar

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

Exercício 3 - Crie um array de 3 dimensões e imprima a dimensão 1

In [49]:
np.arange(12).reshape((3, 4))[0]

array([0, 1, 2, 3])

Exercício 4 - Crie um array de duas dimensões (matriz). Imprima os elementos da terceira linha da matriz. Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [86]:
import numpy as np
array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
array2D[2]

array([7, 8, 9])

In [84]:
array2D[:2, :1]

array([[1],
       [4]])

Exercício 5 - Calcule a transposta da matriz abaixo

In [8]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Exercício 6 - Considere os 3 arrays abaixo; Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.

In [94]:
import numpy as np

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

1.1

In [97]:
cont = 0
lista = []
for val in cond:
    if val == True:
        lista.append(xarr[cont])
    else:
        lista.append(yarr[cont])
        
    cont = cont+1
    
lista

[1.1, 2.2, 1.3, 1.4, 2.5]

In [98]:
# Solução Proposta
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

Exercício 7 - Crie um array A com 10 elementos e salve o array em disco com a extensão npy. Depois carregue o array do disco no array B;

In [103]:
import numpy as np
A = np.arange(10)
print(A)
np.save('array_a', A)
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Exercício 8 - Considerando a série abaixo, imprima os valores únicos na série;

In [75]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [77]:
unicos = obj.unique()
unicos

array(['c', 'a', 'd', 'b'], dtype=object)

Exercício 9 - Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.

In [105]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [107]:
data = resp.json()
data[0]['title']

'BUG: Rounding on float16 type not working'

In [108]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    35124          BUG: Rounding on float16 type not working   
1    35123  BUG: pandas does not build on AIX - when using...   
2    35122                 CLN: remove kwargs in Index.format   
3    35121              TST add test case for drop_duplicates   
4    35120   TYP, DOC, CLN:SeriesGroupBy._wrap_applied_output   
5    35119                 REF: make ccalendar self-contained   
6    35118  CLN: Index._format_with_header (remove kwargs ...   
7    35116                                TST: Extension base   
8    35114  BUG: get_loc with time object matching NaT micros   
9    35113                           PERF: ints_to_pydatetime   
10   35112  BUG: Mixed DataFrame with Extension Array inco...   
11   35111   BUG: reset_index is passing a bad dtype to NumPy   
12   35109  BUG: Groupby.transform on datetime with nuniqu...   
13   35108           REF: implement tz_localize_to_utc_single   
14   35107                                 TYP: get_utcoffset   
15   35106             PERF: tz_localize(None) from dst, asvs   
16   35104                 CLN: tz_convert is always from UTC   
17   35103                                  TYP: maybe_get_tz   
18   35102           REF: standardize tz_convert_single usage   
19   35100           Document Tips for Debugging C Extensions   
20   35099                              TYP: type unit as str   
21   35098  BUG: fix union_indexes not supporting sort=Fal...   
22   35097  QST: Does the following method have circular d...   
23   35095   BUG: reset_index is passing a bad dtype to NumPy   
24   35092  BUG: DataFrame.append seems to be sorting colu...   
25   35090                TST: update gbq service account key   
26   35085                                  Fix numpy warning   
27   35083            No fastcall attribute in POWER platform   
28   35080  BUG: Strange behavior at testing test_ts_plot_...   
29   35078  BUG: DataFrameGroupBy.__getitem__ fails to pro...   

                                               labels state  
0   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
1   [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
2                                                  []  open  
3                                                  []  open  
4                                                  []  open  
5   [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
6   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
7                                                  []  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
10  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open  
11  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
12  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
13  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
14  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
15  [{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...  open  
16  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
17  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
18  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
19  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
20  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...  open  
23  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 57351315, 'node_id': 'MDU6TGFiZWw1NzM1...  open  
26  [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
27  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
28  [{'id': 76939933, 'node_id': 'MDU6TGFiZWw3Njkz...  open  
29  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open

Exercício 10 - Crie um banco de dados no SQLite, crie uma tabela, insira registros, consulte a tabela e retorne os dados em dataframe do Pandas.

In [109]:
# Remove o arquivo com o banco de dados SQLITE (caso exista)
import os
os.remove("abaduba.db") if os.path.exists("abaduba.db") else None

In [110]:
# Importando o módulo de acesso ao SQLLite
import sqlite3

In [111]:
# Cria uma conexão com o banco de dados.
# Se o banco de dados não exists, ele é criando neste momento.
con = sqlite3.connect('abaduba.db')

In [113]:
# Criando um cursor
# Um cursos permite percorrer todos os registros em um conjunto de dados
cur = con.cursor()

In [115]:
# Cria e executa instrução SQL CREATE TABLE
sql_create = 'create table aba (id integer primary key, coluna varchar(100))'
cur.execute(sql_create)

In [122]:
# Cria e instrução SQL INSERT INTO
sql_insert = 'insert into aba values (?, ?)'

In [123]:
# Dados
recset = [(1, 'Abadub'),
         (2, 'Budababa')]

In [124]:
# Inserindo os registros
for rec in recset:
    cur.execute(sql_insert, rec)

In [125]:
# Grava a transação
con.commit()

In [130]:
# Crie e executa instrução SQL SELECT (e recupera os registros)
sql_select = 'select * from aba'
cur.execute(sql_select)
dados = cur.fetchall()

for linha in dados:
    print('id: %d, coluna: %s \n' % linha)

id: 1, coluna: Abadub 

id: 2, coluna: Budababa 



In [136]:
import pandas as pd
abaduba = pd.DataFrame(dados, columns=['id', 'coluna'])
abaduba

id    coluna
0   1    Abadub
1   2  Budababa

In [137]:
# Grava a transação e fecha a conexão
con.commit()
con.close()