Exercício 1 - Crie um array NumPy com 1000000 e uma lista com 1000000. Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time). Qual objeto oferece melhor performance, array NumPy ou lista?

Exercício 2 - Crie um array de 10 elementos. Altere o valores de todos os elementos dos índices 5 a 8 para 0;

In [35]:
import numpy as np

In [36]:
ar = np.arange(10)

In [37]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
type(ar)

numpy.ndarray

In [39]:
ar[5:9] = 0

In [40]:
ar

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

Exercício 3 - Crie um array de 3 dimensões e imprima a dimensão 1

In [49]:
np.arange(12).reshape((3, 4))[0]

array([0, 1, 2, 3])

Exercício 4 - Crie um array de duas dimensões (matriz). Imprima os elementos da terceira linha da matriz. Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

Exercício 5 - Calcule a transposta da matriz abaixo

In [8]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Exercício 6 - Considere os 3 arrays abaixo; Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.

In [9]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Exercício 7 - Crie um array A com 10 elementos e salve o array em disco com a extensão npy. Depois carregue o array do disco no array B;

Exercício 8 - Considerando a série abaixo, imprima os valores únicos na série;

In [10]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

Exercício 9 - Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.

In [11]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

Exercício 10 - Crie um banco de dados no SQLite, crie uma tabela, insira registros, consulte a tabela e retorne os dados em dataframe do Pandas.